---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include_tasks: install.yml
  tags: filebeat_install

- include_tasks: config.yml
  tags: filebeat_config
  when: filebeat_config_enabled

- include_tasks: template.yml
  tags: filebeat_template

- name: Ensure Filebeat is enabled and started at boot
  service:
    name: filebeat
    enabled: yes
    state: started
  when: filebeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
